/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tuiter;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Elisa Vasquez 
 */
public class MenuPrincipal extends javax.swing.JFrame {
    //Declaracion de Variables 
    RandomAccessFile Twits;
    RandomAccessFile User;
    RandomAccessFile Follows;

    private final String Mensaje = "No has Escrito Nada";

    String username;
    ArrayList<String> UsuarioVisitar;
    CuentaActual CuentaUsuario;

    public MenuPrincipal(String Username) {
        this.username = Username;
        CuentaUsuario = new CuentaActual(username);
        UsuarioVisitar = new ArrayList();
        String Us;
        try {
            User = new RandomAccessFile("src\\Datos del Programa\\Usuarios.twc", "rw");
            User.seek(0);
            while (User.getFilePointer() < User.length()) {

                User.readUTF();
                User.readChar();

                Us = User.readUTF();

                User.readUTF();

                User.skipBytes(12);
                if (User.readBoolean()) {

                    UsuarioVisitar.add(Us);
                }

            }

        } catch (IOException e) {
            System.out.println("Error");
        }

        try {
            File files = new File("src\\Datos del Programa");
            files.mkdirs();

            Twits = new RandomAccessFile("src\\Datos del Programa\\" + Username + "\\" + "twits.twc", "rw");
            Follows = new RandomAccessFile("src\\Datos del Programa\\" + Username + "\\" + "following.twc", "rw");
            setIconImage(new ImageIcon(getClass().getResource("/Imagenes del Programa/iconT.png")).getImage());
            initComponents();
            this.setLocationRelativeTo(null);
            Image mImagen = new ImageIcon("src\\Datos del Programa\\" + username + "\\" + "Perfil").getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(ImagPerfil.getWidth(), ImagPerfil.getHeight(), Image.SCALE_SMOOTH));

            ImagPerfil.setIcon(mIcono);

            ImageIcon mIcono2 = new ImageIcon(mImagen.getScaledInstance(IMAGENP.getWidth(), IMAGENP.getHeight(), Image.SCALE_SMOOTH));

            IMAGENP.setIcon(mIcono2);

            Nombre.setText(Username);
            Arroba.setText("@" + Username);

            //Areade_Texto.setText(MostrarTuits());
            ArrayList<ControlDeTwits> ListaTemporal = new ArrayList<>();

            Collections.sort(CuentaUsuario.MostrarTwits(ListaTemporal, Twits));

            String Twiteado = CuentaUsuario.ImprimirTwits(ListaTemporal, "", 0);

            Areade_Texto.setText(Twiteado);

        } catch (IOException e) {
            System.out.println("Error RandomAccess Menu Principal");
        }

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Areade_Texto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TUIT = new javax.swing.JTextArea();
        Nombre = new javax.swing.JLabel();
        Arroba = new javax.swing.JLabel();
        Tuitear = new javax.swing.JButton();
        CerrarSesion = new javax.swing.JButton();
        EditarPerfil = new javax.swing.JButton();
        Boton_Interacciones = new javax.swing.JButton();
        BotonHashtag = new javax.swing.JButton();
        BotonCambiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ImagPerfil = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IMAGENP = new javax.swing.JLabel();
        TIMELINE = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Areade_Texto.setBackground(new java.awt.Color(255, 255, 255));
        Areade_Texto.setColumns(20);
        Areade_Texto.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        Areade_Texto.setForeground(new java.awt.Color(0, 0, 0));
        Areade_Texto.setLineWrap(true);
        Areade_Texto.setRows(5);
        Areade_Texto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        jScrollPane1.setViewportView(Areade_Texto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 590, 740));

        TUIT.setBackground(new java.awt.Color(255, 255, 255));
        TUIT.setColumns(20);
        TUIT.setLineWrap(true);
        TUIT.setRows(5);
        TUIT.setTabSize(10);
        jScrollPane2.setViewportView(TUIT);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 510, 60));

        Nombre.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("User Name");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 290, 110));

        Arroba.setBackground(new java.awt.Color(153, 153, 153));
        Arroba.setForeground(new java.awt.Color(153, 153, 153));
        Arroba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Arroba.setText("@UserName");
        getContentPane().add(Arroba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 290, 30));

        Tuitear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/MandarTuit.png"))); // NOI18N
        Tuitear.setBorder(null);
        Tuitear.setBorderPainted(false);
        Tuitear.setContentAreaFilled(false);
        Tuitear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TuitearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TuitearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TuitearMouseExited(evt);
            }
        });
        Tuitear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuitearActionPerformed(evt);
            }
        });
        getContentPane().add(Tuitear, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 190, 50));

        CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/CerrarSesion.png"))); // NOI18N
        CerrarSesion.setBorder(null);
        CerrarSesion.setBorderPainted(false);
        CerrarSesion.setContentAreaFilled(false);
        CerrarSesion.setFocusPainted(false);
        CerrarSesion.setFocusable(false);
        CerrarSesion.setRequestFocusEnabled(false);
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseExited(evt);
            }
        });
        getContentPane().add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 742, 300, 50));

        EditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/EditarP.png"))); // NOI18N
        EditarPerfil.setBorder(null);
        EditarPerfil.setBorderPainted(false);
        EditarPerfil.setContentAreaFilled(false);
        EditarPerfil.setFocusPainted(false);
        EditarPerfil.setFocusable(false);
        EditarPerfil.setRequestFocusEnabled(false);
        EditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarPerfilMouseExited(evt);
            }
        });
        EditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(EditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 210, -1));

        Boton_Interacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/Interacciones.png"))); // NOI18N
        Boton_Interacciones.setBorder(null);
        Boton_Interacciones.setBorderPainted(false);
        Boton_Interacciones.setContentAreaFilled(false);
        Boton_Interacciones.setFocusPainted(false);
        Boton_Interacciones.setFocusable(false);
        Boton_Interacciones.setRequestFocusEnabled(false);
        Boton_Interacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_InteraccionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_InteraccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_InteraccionesMouseExited(evt);
            }
        });
        getContentPane().add(Boton_Interacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 210, -1));

        BotonHashtag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/Hashtag.png"))); // NOI18N
        BotonHashtag.setBorder(null);
        BotonHashtag.setBorderPainted(false);
        BotonHashtag.setContentAreaFilled(false);
        BotonHashtag.setFocusPainted(false);
        BotonHashtag.setFocusable(false);
        BotonHashtag.setRequestFocusEnabled(false);
        BotonHashtag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonHashtagMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHashtagMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHashtagMouseExited(evt);
            }
        });
        getContentPane().add(BotonHashtag, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 190, -1));

        BotonCambiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/BotonCambiar.png"))); // NOI18N
        BotonCambiar.setBorder(null);
        BotonCambiar.setBorderPainted(false);
        BotonCambiar.setContentAreaFilled(false);
        BotonCambiar.setFocusPainted(false);
        BotonCambiar.setFocusable(false);
        BotonCambiar.setRequestFocusEnabled(false);
        BotonCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCambiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCambiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCambiarMouseExited(evt);
            }
        });
        BotonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambiarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 210, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/ImagenparaPerfil2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 230));

        ImagPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/Perfil.jpg"))); // NOI18N
        ImagPerfil.setText("IMAGEN");
        getContentPane().add(ImagPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 230));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/IMAGENPEQUEÑA.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 50, -1));
        getContentPane().add(IMAGENP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 50, 50));

        TIMELINE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/Timeline.png"))); // NOI18N
        TIMELINE.setBorder(null);
        TIMELINE.setBorderPainted(false);
        TIMELINE.setContentAreaFilled(false);
        TIMELINE.setFocusPainted(false);
        TIMELINE.setFocusable(false);
        TIMELINE.setRequestFocusEnabled(false);
        TIMELINE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TIMELINEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TIMELINEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TIMELINEMouseExited(evt);
            }
        });
        TIMELINE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIMELINEActionPerformed(evt);
            }
        });
        getContentPane().add(TIMELINE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 293, 210, 50));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes del Programa/fotor_2023-3-19_19_22_31.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void TuitearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TuitearMouseClicked

        if (!TUIT.getText().equals("")) {
            if (TUIT.getText().length() <= 140) {
                try {

                    CuentaUsuario.HacerTwit(username, TUIT.getText());
                    // Areade_Texto.setText("");
                    //    Areade_Texto.setText(MostrarTuits());

                } catch (IOException e) {
                    System.out.println("Error!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Son demasiadas palabras");
            }
        } else {
            JOptionPane.showMessageDialog(null, Mensaje);
        }
        TUIT.setText("");


    }//GEN-LAST:event_TuitearMouseClicked

    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        // this.setVisible(false);

        Login L = new Login();
        L.setVisible(true);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_CerrarSesionMouseClicked

    private void EditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarPerfilMouseClicked
        Editar_Perfil EP = new Editar_Perfil(username);
        EP.setVisible(true);
    }//GEN-LAST:event_EditarPerfilMouseClicked

    private void Boton_InteraccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_InteraccionesMouseClicked
        try {
            ArrayList<ControlDeTwits> ListaTemporal_Interaccion = new ArrayList();

            for (String UV : UsuarioVisitar) {

                RandomAccessFile Usuarios = new RandomAccessFile("src\\Datos del Programa\\" + UV + "\\" + "twits.twc", "rw");

                while (Usuarios.getFilePointer() < Usuarios.length()) {

                    Calendar Fecha = Calendar.getInstance();
                    String UsuarioSeguido1 = Usuarios.readUTF();
                    String MensajeSeguido = Usuarios.readUTF();
                    Long FechaSeguido = Usuarios.readLong();
                    Fecha.setTimeInMillis(FechaSeguido);

                    if (MensajeSeguido.contains("@" + username)) {
                        ListaTemporal_Interaccion.add(new ControlDeTwits(UsuarioSeguido1, MensajeSeguido, Fecha));
                    }

                }

            }

            Collections.sort(ListaTemporal_Interaccion);

            String Twiteado = "";
            for (ControlDeTwits CT : ListaTemporal_Interaccion) {
                Twiteado += CT.getUsuario() + " Escribio: \n\n"
                        + "¨ " + CT.getMensaje() + " ¨" + "\n\n el [" + CT.getFecha().getTime() + "]\n\n\n";

            }

            try {
                if (Twiteado.equals("")) {
                    throw new NullPointerException("No Han Habido Interacciones");
                } else {

                }
                JOptionPane.showMessageDialog(null, Twiteado);

            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        } catch (IOException ex) {

        }

    }//GEN-LAST:event_Boton_InteraccionesMouseClicked

    private void BotonHashtagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHashtagMouseClicked
        String Hashtag = JOptionPane.showInputDialog(null, "Ingrese el #");
        try {
            if (Hashtag.equals("")) {
                throw new NullPointerException(Mensaje);
            } else {
                try {
                    ArrayList<ControlDeTwits> ListaTemporal_Hashtag = new ArrayList();
                    for (String UV : UsuarioVisitar) {

                        RandomAccessFile Usuarios = new RandomAccessFile("src\\Datos del Programa\\" + UV + "\\" + "twits.twc", "rw");

                        while (Usuarios.getFilePointer() < Usuarios.length()) {

                            Calendar Fecha = Calendar.getInstance();
                            String UsuarioSeguido1 = Usuarios.readUTF();
                            String MensajeSeguido = Usuarios.readUTF();
                            System.out.println(MensajeSeguido);
                            Long FechaSeguido = Usuarios.readLong();
                            Fecha.setTimeInMillis(FechaSeguido);

                            if (MensajeSeguido.contains("#" + Hashtag)) {
                                ListaTemporal_Hashtag.add(new ControlDeTwits(UsuarioSeguido1, MensajeSeguido, Fecha));
                            }

                        }

                    }
                    System.out.println(ListaTemporal_Hashtag);

                    Collections.sort(ListaTemporal_Hashtag);

                    String Twiteado = "";
                    for (ControlDeTwits CT : ListaTemporal_Hashtag) {
                        Twiteado += CT.getUsuario() + " Escribio: \n\n"
                                + "¨ " + CT.getMensaje() + " ¨" + "\n\n el [" + CT.getFecha().getTime() + "]\n\n\n";

                    }

                    if(Twiteado.equals("")){
                           throw new NullPointerException("No Se Encontro Ningun Hashtag");
                    }
                    
                     JOptionPane.showMessageDialog(null, Twiteado);

                } catch (IOException ex) {
                    System.out.println("Error HASHTAG");
                }
            }

        } catch (NullPointerException e) {

            if (e.getMessage() == null) {
                JOptionPane.showMessageDialog(null, Mensaje);
            } else {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }


    }//GEN-LAST:event_BotonHashtagMouseClicked


    private void BotonCambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCambiarMouseClicked
        JFileChooser JF = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JGP, PNG & GIF", "jpg", "png", "gif");
        JF.setFileFilter(filtrado);
        JF.setMultiSelectionEnabled(false);

        if (JF.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            rsdragdropfiles.RSDragDropFiles.setCopiar(JF.getSelectedFile().toString(), "src\\Datos del Programa\\" + username + "\\" + "Perfil");

            Image mImagen = new ImageIcon(JF.getSelectedFile().getPath()).getImage();

            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(ImagPerfil.getWidth(), ImagPerfil.getHeight(), Image.SCALE_SMOOTH));

            ImagPerfil.setIcon(mIcono);

            ImageIcon mIcono2 = new ImageIcon(mImagen.getScaledInstance(IMAGENP.getWidth(), IMAGENP.getHeight(), Image.SCALE_SMOOTH));

            IMAGENP.setIcon(mIcono2);
        }

    }//GEN-LAST:event_BotonCambiarMouseClicked

    private void BotonCambiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCambiarMouseEntered
        BotonCambiar.setIcon(new ImageIcon("src/Imagenes del Programa/BotonCambiar2.png"));
    }//GEN-LAST:event_BotonCambiarMouseEntered

    private void BotonCambiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCambiarMouseExited
        BotonCambiar.setIcon(new ImageIcon("src/Imagenes del Programa/BotonCambiar.png"));
    }//GEN-LAST:event_BotonCambiarMouseExited

    private void BotonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCambiarActionPerformed

    private void EditarPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarPerfilMouseEntered
        EditarPerfil.setIcon(new ImageIcon("src/Imagenes del Programa/EditarP2.png"));
    }//GEN-LAST:event_EditarPerfilMouseEntered

    private void EditarPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarPerfilMouseExited
        EditarPerfil.setIcon(new ImageIcon("src/Imagenes del Programa/EditarP.png"));
    }//GEN-LAST:event_EditarPerfilMouseExited

    private void BotonHashtagMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHashtagMouseEntered
        BotonHashtag.setIcon(new ImageIcon("src/Imagenes del Programa/Hashtag2.png"));
    }//GEN-LAST:event_BotonHashtagMouseEntered

    private void BotonHashtagMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHashtagMouseExited
        BotonHashtag.setIcon(new ImageIcon("src/Imagenes del Programa/Hashtag.png"));
    }//GEN-LAST:event_BotonHashtagMouseExited

    private void Boton_InteraccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_InteraccionesMouseEntered
        Boton_Interacciones.setIcon(new ImageIcon("src/Imagenes del Programa/Interacciones2.png"));
    }//GEN-LAST:event_Boton_InteraccionesMouseEntered

    private void Boton_InteraccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_InteraccionesMouseExited
        Boton_Interacciones.setIcon(new ImageIcon("src/Imagenes del Programa/Interacciones.png"));
    }//GEN-LAST:event_Boton_InteraccionesMouseExited

    private void CerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseEntered
        CerrarSesion.setIcon(new ImageIcon("src/Imagenes del Programa/CerrarSesion2.png"));
    }//GEN-LAST:event_CerrarSesionMouseEntered

    private void CerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseExited
        CerrarSesion.setIcon(new ImageIcon("src/Imagenes del Programa/CerrarSesion.png"));
    }//GEN-LAST:event_CerrarSesionMouseExited

    private void TuitearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TuitearMouseEntered
        Tuitear.setIcon(new ImageIcon("src/Imagenes del Programa/MandarTuit2.png"));
    }//GEN-LAST:event_TuitearMouseEntered

    private void TuitearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TuitearMouseExited
        Tuitear.setIcon(new ImageIcon("src/Imagenes del Programa/MandarTuit.png"));
    }//GEN-LAST:event_TuitearMouseExited

    private void TIMELINEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TIMELINEMouseEntered
        TIMELINE.setIcon(new ImageIcon("src/Imagenes del Programa/Timeline2.png"));
    }//GEN-LAST:event_TIMELINEMouseEntered

    private void TIMELINEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TIMELINEMouseExited
        TIMELINE.setIcon(new ImageIcon("src/Imagenes del Programa/Timeline.png"));
    }//GEN-LAST:event_TIMELINEMouseExited


    private void TIMELINEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TIMELINEMouseClicked
        try {
            // Areade_Texto.setText(MostrarTuits());
            ArrayList<ControlDeTwits> ListaTemporal = new ArrayList<>();

            Collections.sort(CuentaUsuario.MostrarTwits(ListaTemporal, Twits));

            String Twiteado = CuentaUsuario.ImprimirTwits(ListaTemporal, "", 0);

            Areade_Texto.setText(Twiteado);

        } catch (IOException e) {

        }

    }//GEN-LAST:event_TIMELINEMouseClicked

    private void TuitearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuitearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuitearActionPerformed

    private void TIMELINEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIMELINEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIMELINEActionPerformed

    private void EditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Areade_Texto;
    private javax.swing.JLabel Arroba;
    private javax.swing.JButton BotonCambiar;
    private javax.swing.JButton BotonHashtag;
    private javax.swing.JButton Boton_Interacciones;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton EditarPerfil;
    private javax.swing.JLabel IMAGENP;
    private javax.swing.JLabel ImagPerfil;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton TIMELINE;
    private javax.swing.JTextArea TUIT;
    private javax.swing.JButton Tuitear;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
